# Generated by Django 2.1.7 on 2019-03-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='from_user',
            new_name='author',
        ),
    ]
