# Generated by Django 2.1.7 on 2019-03-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190316_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_text',
        ),
        migrations.AddField(
            model_name='article',
            name='article_body',
            field=models.FileField(default='', upload_to='articles\\body'),
            preserve_default=False,
        ),
    ]
