# Generated by Django 2.1.7 on 2019-03-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_body',
            new_name='body',
        ),
    ]
