# Generated by Django 2.1.7 on 2019-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190318_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code',
            field=models.FileField(blank=True, null=True, upload_to='articles\\body'),
        ),
    ]
