# Generated by Django 2.1.7 on 2019-03-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(default='Python 3', max_length=20),
            preserve_default=False,
        ),
    ]
