# Generated by Django 2.1.7 on 2019-03-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('prime_number', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
