# Generated by Django 2.1.7 on 2019-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='return_address',
            field=models.EmailField(default='null@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
