# Generated by Django 2.1.7 on 2019-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactsubmission_return_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='prime_number',
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='return_address',
            field=models.EmailField(max_length=254, verbose_name='Please Enter YOUR Email Address'),
        ),
    ]
