version: "3.7"
services:

  aboutme-django:
    build: .
    volumes:
      - ./project:/src
    expose:
      - "8000"
    restart: always

  aboutme-data:
    image: postgres
    ports:
      - "5432"
    
  aboutme-proxy:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./config/uwsgi-proxy:/etc/nginx/conf.d
    depends_on:
      - aboutme-django

      