version: "3"
services:
  aboutme-django:
    build: .
    volumes:
      - django-static:/aboutme-django/static/
      - django-media:/aboutme-django/aboutme/
    expose:
      - "8080"
    restart: always

  aboutme-data:
    image: postgres
    ports:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data
    
  aboutme-proxy:
    image: nginx
    ports:
      - "80:8000"
    volumes:
      - ./config/uwsgi-proxy.conf:/etc/nginx/nginx.conf
      - django-static:/aboutme-django/static/
    depends_on:
      - aboutme-django

volumes:
  django-static:
  django-media:
  database: