version: "3"
services:
  aboutme-django:
    build:
      context: .
    volumes:
      - django-static:/aboutme-django/static/
      - django-media:/aboutme-django/aboutme/media/
    expose:
      - "8080"
    restart: always

  aboutme-data:
    image: postgres
    ports:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data
    
  aboutme-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - django-static:/aboutme-django/static/
      - ./config/uwsgi-certbot-proxy.conf:/etc/nginx/nginx.conf
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/html:/var/www/certbot
      - ./config/nginx/log:/var/log/nginx
    depends_on:
      - aboutme-django

  aboutme-cert:
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/html:/var/www/certbot
      - ./config/certbot/log/:/var/log/letsencrypt

volumes:
  django-static:
  django-media:
  database:
