version: "3"
services:
  aboutme-django:
    build: .
    volumes:
      - django-static:/aboutme-django/static/
    expose:
      - "8080"
    restart: always

  aboutme-data:
    image: postgres
    ports:
      - "5432"
    
  aboutme-proxy:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/uwsgi-proxy.conf:/etc/nginx/nginx.conf
      - django-static
    depends_on:
      - aboutme-django
