version: "3"
services:
  aboutme-django:
    build:
      context: .
    volumes:
      - django-static:/aboutme-django/static/
      - django-media:/aboutme-django/aboutme/media/
    expose:
      - "8080"
    restart: always

  aboutme-data:
    image: postgres
    ports:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data
    
  aboutme-proxy:
    build:
      context: ./config/aboutme-proxy/
    ports:
      - "80:8000"
    volumes:
      - django-static:/aboutme-django/static/
    depends_on:
      - aboutme-django

volumes:
  django-static:
  django-media:
  database:
